export enum EUserRoles {
  BLOCK_USER = 'BLOCK_USER',
  UNBLOCK_USER = 'UNBLOCK_USER',

  COUNTRY_CREATE = 'COUNTRY_CREATE',
  COUNTRY_DELETE = 'COUNTRY_DELETE',
  COUNTRY_UPDATE = 'COUNTRY_UPDATE',
}
