#!/bin/sh
if ! head -1 "$1" | grep -qE "^((m|M)erge|(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|content)(\(.+?\))?:) .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid.(Please, check README.md)" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi